# Generated by Django 3.0.5 on 2021-08-02 22:42

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('result', models.CharField(blank=True, choices=[('П', 'Положительный'), ('О', 'Отрицательный')], max_length=50, null=True, verbose_name='Исход')),
            ],
            options={
                'verbose_name': 'Случай лечения',
                'verbose_name_plural': 'Случаи лечения',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=50, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Case', verbose_name='Случай лечения')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Медицинский документ',
                'verbose_name_plural': 'Медицинские документы',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='data.Patient', verbose_name='пациент'),
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', jsonfield.fields.JSONField(default=dict)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Document', verbose_name='Документ')),
            ],
        ),
    ]
