# Generated by Django 3.0.5 on 2021-08-03 11:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name': 'Тело документа', 'verbose_name_plural': '4. Тело документов'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Случай лечения', 'verbose_name_plural': '2. Случаи лечения'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Медицинский документ', 'verbose_name_plural': '3. Медицинские документы'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': '1. Пациенты'},
        ),
        migrations.AlterField(
            model_name='body',
            name='content',
            field=jsonfield.fields.JSONField(default=dict, verbose_name='Контент'),
        ),
    ]
